spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuanba?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall,slf4j     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  redis:
    host: localhost
    port: 6379
    timeout: 2000s
mybatis:
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
  type-aliases-package: com.zb.pojo  # 开启别名
  config-location: classpath:mybatis-config.xml

# 配置pageHelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql