spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuanba?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 2000s
mybatis:
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
  type-aliases-package: com.zb.pojo  # 开启别名
  config-location: classpath:mybatis-config.xml

# 配置pageHelper参数
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql